name: Daily Review Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Tato verze už Node.js 20 nehlásí!

      - name: Set up Python
        uses: actions/setup-python@v5 # Tato verze je taky aktuální
        with:
          python-version: '3.10'

      - name: Install libraries DIRECTLY
        run: |
          pip install pandas playwright streamlit plotly
          playwright install chromium

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'Scraper Bot'
          git config --global user.email 'bot@goodnite.cz'
          git add .
          git commit -m "Automatická aktualizace recenzí" || exit 0
          git push
