name: Daily Review Scrape

on:
  schedule:
    - cron: '0 7 * * *' # Běží každý den v 7:00 UTC (8:00 našeho času)
  workflow_dispatch: # Umožňuje spustit ručně tlačítkem

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'Scraper Bot'
          git config --global user.email 'bot@goodnite.cz'
          git add .
          git commit -m "Automatická aktualizace recenzí"
          git push
